### ISSUE TITLE
Adjustments to Flat Check

### ISSUE THREAD

**Issue by cchopps** [jessev14/pf2-flat-check#10]
Is there a way to add bonuses to the flat check (or adjust the DC) for abilities that do so? For example, a Magus with "Starlit Eyes" reduces the flat check against hidden or concealed creatures when making ranged strikes. Thank you!

**Comment by jessev14** [comment]
It's my understanding that flat checks are supposed to be just that, flat. And that the DCs are fixed based on the relevant condition.

It would be possible to make these values dynamic depending on other factors, but it's not really my call to implement this feature.

This module was funded by a commission so any additional work on this module would have to be 1) Allowed by the original commissioner (`ApoApostolov#4622`) and 2) Funded (does not necessarily have to be funded by the original commissioner).

I would recommend reaching out to ApoApostolov to see if this feature is something they would want to see in this module.

**Comment by cchopps** [comment]
There are a few things that tweak them. They technically don't give bonuses to the roll but they change the DC. A Magus with "Starlit Eyes" in their "Arcane Cascade Stance" and all Halflings (with Keen Eyes) reduce the DC of the flat check to 3 for a concealed target or 9 for a hidden one.

I'll reach out to the original commissioner.

**Comment by cchopps** [comment]
I emailed with Apostol and he gives his permission to update. He may want to be involved in the discussion. My email is cchopps at gmail if you would like to discuss moving forward. Thank you!

**Comment by jessev14** [comment]
Will need quite a bit of detail to implement this and quote a cost. Discord `enso#0361` is the best place to reach me.
