### ISSUE TITLE
flat check not working

### ISSUE THREAD

**Issue by belkasro** [jessev14/pf2-flat-check#13]
updated to V10 build 288 PF2e V4.2.6. has it not made compatible yet or something else am I missing

**Comment by jessev14** [comment]
It's been made compatible for the latest Foundry and system version and has been reported to work on those versions.

A bit more detail would be helpful.

Nothing appears when you make an attack roll with a target with the Concealed condition?
Are there any errors in the console?

**Comment by belkasro** [comment]
![flat check error](https://user-images.githubusercontent.com/104159350/195693721-7c4e7c3c-5bb7-48c7-aa78-bad7baa07749.JPG)

hope this helps

**Comment by belkasro** [comment]
when i attacked invisible or anything that makes it harder to hit it does nothing

**Comment by jessev14** [comment]
Ah, I see the issue. I've fixed it in version 1.4.2, which should be available to update now.
