### ISSUE TITLE
See Invisibility Doesn't Downgrade Flat Check DC

### ISSUE THREAD

**Issue by gfactor** [jessev14/pf2-flat-check#14]
When a target is Invisible, an attacker must pass a DC 11 Flat Check. However, if the attacker has See Invisibility, the attacker considers an Invisible creature as Concealed instead, reducing the Flat Check DC to 5. The PF2 Flat Check module does not account for this situation.

You can create this situation in Foundry VTT with 2 actors. Give one of the actors (the target) the Invisible condition, give the other one (the attacker) the Spell Effect: See Invisibility (which grants the seeInvisibility Sense to that actor), then have the attacker attack the target.

**Comment by jessev14** [comment]
This module was funded by a commission. I only implemented the flat check cases in the conditions that the commissioner outlined.

I am happy to merge PRs that implement other cases, as I've already done.

If you want to discuss funding additional implementations to this module, feel free to reach out to me on discord: `enso#0361`.
